<section class="hero bg-cover bg-position py-4" style="background: url(img/bi2.jpg); height: 100vh;">
    <div class="container py-5 index-forward text-white" style="margin-top: 100px">
        <h1>Business Intelligence Systems</h1>
        <!-- Breadcrumb-->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-none mb-0 p-0">
                <li class="breadcrumb-item pl-0"><a href="index.php"> <i class="fas fa-home mr-2"></i>Home</a></li>
                <li class="breadcrumb-item text-light" aria-current="page">Solutions</li>
            </ol>
        </nav>
    </div>
</section>


<section class="py-5">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-6">
                <h5 class=" mb-1 text-uppercase mb-3" style="color: #003A78;">Business Intelligence Systems</h5>
                <p class="text-small text-muted">Turning the vast amounts of data collected everyday into value, is a key success factor for companies. We have the know-how to transform the data generated by our control systems into rich information that enables smart choices to cut costs, optimise their processes and increase throughput.</p>

                <p class="text-small text-muted">Our Business Intelligence Systems are designed to provide clients with the information they need, when they need it. These systems give clients data that, once analysed, assists in bottle-neck identification and plant optimization, leading to increased production.</p>

                <p class="text-small text-muted">Anotuim BIS solutions enable you to:</p>
                <ul class="list-check list-unstyled row px-3 mb-4">
                    <li class="text-small text-muted col-12 mb-2">Increase overall plant throughput</li>
                    <li class="text-small text-muted col-12 mb-2">Monitor equipment performance</li>
                    <li class="text-small text-muted col-12 mb-2">Record equipment effectiveness</li>
                    <li class="text-small text-muted col-12 mb-2">Provide production reports</li>
                    <li class="text-small text-muted col-12 mb-2">Reduce waste, re-work and scrap</li>
                    <li class="text-small text-muted col-12 mb-2">Capture costs</li>
                    <li class="text-small text-muted col-12 mb-2">Increase uptime</li>

                </ul>
            </div>
            <div class="col-lg-5 mb-4 mb-lg-0">
                <div class="pt-1"><img class="img-fluid" src="img/bi.jpg" alt=""></div>
            </div>
        </div>
    </div>
</section>